name: "MandandoEmail"
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: check conteudo do repositorio
        uses: actions/checkout@v3

      - name: instalar python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: instalar os pacotes do requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Edit .env file
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Executa arquivo principal
        run: robot -d reports -v email_password:${{ secrets.EMAIL_PASSWORD }} execute.robot