name: "Example"
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to PostgreSQL
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432


          
